### ISSUE TITLE
No such file or directory, copyfile refs.terrain.json -> frontend/src/...

### ISSUE THREAD

**Issue by peterpme** [am-work/terra-homework#3]
Is it possible to prevent this copy from running? If not, I can create a PR that updates the text to acknowledge the error is ok

Thanks!

```
    Error: ENOENT: no such file or directory, copyfile './refs.terrain.json' -> './frontend/src/refs.terrain.json'
    Code: ENOENT
```

**Comment by am-work** [comment]
That copy is created by `terrain` here: https://github.com/terra-money/terrain/blob/f46e4cf45b4c1485574628550e3cb228f646c424/src/commands/deploy.ts#L90

Unfortunately, they didn't add any flags to skip it. Basically, `terrain` expects you to have a `frontend/src` subdirectory in your codebase. That subdirectory doesn't exist in this repo, so the copy fails. 

That error is harmless in the context of this homework (because we are not building a frontend) but there are two quick and dirty solutions to silence the warning:
1) Pass the `--frontend-refs-path` flag pointing to a path in an existing directory; for example:
```
npx @terra-money/terrain deploy ... --frontend-refs-path=/tmp/unused.json
```
2) Create a `frontend/src` subdirectory:
```
mkdir -p frontend/src
```

I will send a PR adding option 2 to the repo to silence the warning for everyone without polluting the already complicated `terrain` command.
